### ISSUE TITLE
Pager missing from list view

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/sample-dynamic-authorization-policy#4]
The Authorization Policies list view is only showing page the first 10 records.  If I add '?pagesize=10&pagenumber=2' to the url then I can see the others.

![image](https://user-images.githubusercontent.com/10956017/52333911-579b4d00-29f6-11e9-9046-49793aeac220.png)

**Comment by joeaudette** [comment]
fixed in latest nugets, Thanks!
